type Store {
    id: Int
    user_id: Int
    name: String
    site_name: String
    description: String
    type: String
    image: [String]
    status: String
    created_at: DateTime
    updated_at: DateTime
}

input StoreInput {
    user_id: Int
    name: String!
    site_name: String!
    description: String
    type: String
    media_ids: String
    status: STATUS
}

type Query {
    storeFindAll: [Store]
    storeFindAllByUser(user_id: Int): [Store]
    storeFindOne(id: Int): Store
}

type Mutation {
    storeCreate (data: StoreInput!): Store
    storeUpdate (id: Int, data: StoreInput!): Store
    storeDelete (id: Int): Boolean
}
